{{- if and (not .Values.existingSecret) .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admin.fullname" . }}-env
  labels:
    {{- include "admin.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
