apiVersion: v1
kind: Pod
metadata:
  labels:
    app: admin-ci
spec:
  serviceAccountName: jenkins
  securityContext:
    fsGroup: 1000
  containers:
    - name: node
      image: node:20-alpine
      command: ["sh", "-c", "cat"]
      tty: true
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "2"
          memory: "2Gi"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.23.2-debug
      command: ["/busybox/sh", "-c", "cat"]
      tty: true
