apiVersion: v1
kind: Pod
metadata:
  labels:
    app: admin-ci
spec:
  serviceAccountName: jenkins
  securityContext:
    fsGroup: 1000
  containers:
    - name: node
      image: node:20-alpine
      command: ["cat"]
      tty: true
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "2"
          memory: "2Gi"
    - name: docker
      image: docker:27-cli
      command: ["cat"]
      tty: true
      env:
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker
      volumeMounts:
        - name: docker-config
          mountPath: /home/jenkins/.docker
  volumes:
    - name: docker-config
      emptyDir: {}
